providers = ['python']

[phases.build]
cmds = [
    "ls -la",
    "python manage.py compress",
    "python manage.py collectstatic --noinput",
]
[start]
cmd = "gunicorn -b 0.0.0.0:8000 -w 2 --log-level debug --log-file - --access-logfile - fuminsho.wsgi"